spring.application.name=weather
server.port=8081

# RapidAPI Configuration
rapidapi.key=3daaae70c8msh48067969f825d70p1d8549jsnbf90168841c9
rapidapi.host=weather-by-api-ninjas.p.rapidapi.com
rapidapi.url=https://weather-by-api-ninjas.p.rapidapi.com/v1/weather?city=